vich_uploader:
    db_driver: orm

    mappings:
        user_images:
           uri_prefix: '%app.path.user_images%'
           upload_destination: '%kernel.project_dir%/public/assets/images/users/'
        recipe_images:
           uri_prefix: '%app.path.recipe_images%'
           upload_destination: '%kernel.project_dir%/public/assets/images/recipes/'
